FROM python:3.12.5-slim-bookworm 

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

COPY ./ .

RUN pip install --quiet -r requirements.txt

ENTRYPOINT [ "fastapi", "dev", "--host", "0.0.0.0", "--port", "3000", "./sample_api/main.py" ]