name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: compose up
        uses: hoverkraft-tech/compose-action@v2.0.1
        # with:
        #   up-flags: "--profile test"
